### ISSUE TITLE
PyTorch pre-trained weights?

### ISSUE THREAD

**Issue by hurjunhwa** [iwbn/flow-supervisor#2]
Hi, Thanks for the great work!
I was wondering if pretrained weights for pytorch are available.

Best,
Junhwa

**Comment by iwbn** [comment]
Hi, thank you for contacting me.

This is the [link](https://kaistackr-my.sharepoint.com/:u:/g/personal/iwbn_kaist_ac_kr/EWmN7T-YE4RCsf_86OjIib8Bx-fXsqZVa0G02xjqziRnaQ?e=qygJ9a) for downloading pretrained pytorch weights (including benchmark weights). This is a quick release, and I will re-check these files and update the readme file within next few weekdays.

**Comment by hurjunhwa** [comment]
Thank you very much for your fast response 👍👍
